### ISSUE TITLE
Dependency to PyOpenGL missing

### ISSUE THREAD

**Issue by stephan-cr** [abhinav-TB/glpy#2]
I installed glpy via `pip install git+https://github.com/abhinav-TB/glpy`. If I do

```python
import glpy
```
I get
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/stephan/venvs/test/lib/python3.9/site-packages/glpy/__init__.py", line 1, in <module>
    from glpy.main import *
  File "/home/stephan/venvs/test/lib/python3.9/site-packages/glpy/main.py", line 1, in <module>
    from OpenGL.GL import *
ModuleNotFoundError: No module named 'OpenGL'
```

**Comment by abhinav-TB** [comment]
hey @stephan-cr you need to install PyOpenGL for glpy to work since its just a wrapper around the same

**Comment by stephan-cr** [comment]
Usually, packages declare their dependencies. When I look at [setup.py](https://github.com/abhinav-TB/glpy/blob/master/setup.py#L17-L19), the list of `install_requirements` for `setup(...)` is empty, whereas I would expect something like:

```python
INSTALL_REQUIRES = [
    'PyOpenGL'
]
```

**Comment by abhinav-TB** [comment]
@stephan-cr  Installing PyOpengGL is a bit tricky, especially in windows. The version to be downloaded depends on your python version and the processor type (32bit or 64bit) so that's why I didn't add it to the requirements. In future releases, I will consider adding it as a dependency only for Linux .
But it's best to find the version suitable for your system by doing some research, if the pip install didn't work for you, let me know if you find any difficulties with that.

**Comment by stephan-cr** [comment]
> The version to be downloaded depends on your python version and the processor type (32bit or 64bit) so that's why I didn't add it to the requirements.

I think Pip is able to figure that out.

**Comment by abhinav-TB** [comment]
@stephan-cr  in most cases that's true but direct pip install of pyopenGL is buggy in most cases in windows, I have tried it with some volunteers so its best to install it separately
